### ISSUE TITLE
Bump Java version to let CI succeed

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/DWDWeatherTools#105]
Bump Java version to sth. >= 11

_Originally posted by @t-ober in https://github.com/ie3-institute/DWDWeatherTools/issues/96#issuecomment-1037036101_

**Comment by RishiKumarRay** [comment]
@ckittl maybe i am wrong but if CI is being built with jenkins the changing def javaVersionId = 'jdk-8' in jenkins file will fix this issue?

**Comment by sebastian-peter** [comment]
> maybe i am wrong but if CI is being built with jenkins the changing def javaVersionId = 'jdk-8' in jenkins file will fix this issue?

Yes, among other things. You can check out the branch if you
